//Spanish
plupload.addI18n({
    'Select files' : 'Elija archivos:',
    'Add files to the upload queue and click the start button.' : 'Agregue archivos a la cola de subida y haga click en el boton de iniciar.',
    'Filename' : 'Nombre de archivo',
    'Status' : 'Estado',
    'Size' : 'Tamaño',
    'Add files' : 'Agregue ficheros',
    'Stop current upload' : 'Detener la transferencia actual',
    'Start uploading queue' : 'Iniciar transferencia de cola',
    'Drag files here.' : 'Arrastre archivos aqu&iacute;',
    'Start upload' : 'Iniciar transferencia',
    'Uploaded %d/%d files': 'Subidos %d/%d archivos',
    'Stop upload': 'Detener transferencia',
    '%d files queued': '%d archivos en cola',
    'File: %s': 'Archivo: %s',
    'Close': 'Cerrar',
    'Using runtime: ': 'Tecnología en uso: ',
    'File: %f, size: %s, max file size: %m': 'Archivo: %f, tamaño: %s, tamaño máximo permitido: %m',
    'Upload element accepts only %d file(s) at a time. Extra files were stripped.': 'Solo pueden subirse %d archivos al mismo tiempo. Los archivos restantes serán omitidos',
    'Upload URL might be wrong or doesn\'t exist': 'La URL para procesar los archivos parece ser incorrecta o no existe',
    'Error: File too large: ': 'Error: Archivo demasiado grande: ',
    'Error: Invalid file extension: ': 'Error: Extensión no permitida: ',
    'File extension error.': 'Error en la extensión del archivo.',
    'File size error.': 'Error en el peso del archivo.',
    'File count error.': 'Error al contar los archivos.',
    'Init error.': 'Error de iniciación.',
    'HTTP Error.': 'Error HTTP.',
    'Security error.': 'Error de seguridad.',
    'Generic error.': 'error genérico.',
    'IO error.': 'Error I/O.'
});